version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - 8080:80
